- hosts: localhost
  tasks:
  - name: Gather cluster facts from given datacenter
    vmware_cluster_info:
      hostname: dc04vmvc04
      username: your_vceter_user
      password: your_vceter_passwd
      datacenter: DC04VC04
      validate_certs: False
    delegate_to: localhost
    register: cluster_facts

  - name: Gather facts from datacenter about specific cluster
    vmware_cluster_facts:
      hostname: dc04vmvc04
      username: your_vceter_user
      password: your_vceter_passwd
      cluster_name: DC04-VC04-Cluster14
      validate_certs: False
    delegate_to: localhost
    register: cluster_fact
