- hosts: localhost
  gather_facts: no
  vars:
    vcenter_server: "dc04vmvc04"
    vcenter_user: "svc_aut_bld@sfdc"
    vcenter_pass: "9Ym6+b$Hd"
    datacenter_name: "DC04VC04"
    cluster_name: "DC04-VC04-Cluster14"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: SDO-Automation-Test-vm
      template: sles12sp5-04-02-2020-vmxnet
      datacenter: "{{ datacenter_name }}"
      folder: /{{ datacenter_name }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "DC04_VC04_SAS2SSD_Storage_Cluster14"
      networks:
      - name: MGMT-SVCS_198
        hostname: "SDO-Automation-Test-vm"
        dns_servers:
        - 10.4.196.10
        - 10.4.196.46
      state: poweredoff
      wait_for_ip_address: no
    delegate_to: localhost
